version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.9"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"