[versions]
spring-boot = "3.2.5"
kotlin = "1.9.23"
pagehelper = "6.1.0"
pagehelper-starter = "2.1.0"
mybatis = "3.5.16"
spring-mybatis = "3.0.3"
guava = "33.1.0-jre"
easyexcel = "3.3.4"
redisson = "3.29.0"
clickhouse = "0.6.0"
spotbugs-annotations = "4.8.4"
mapstruct = "1.5.5.Final"
mapstruct-lombok = "0.2.0"
curator = "5.6.0"
asciidoctor-jvm = "4.0.2"
browscap-java = "1.4.3"
auto-service = "1.1.1"
yauaa = "7.26.1"
springdoc = "2.5.0"
google-javase = "3.5.3"
spring-admin = "3.2.3"
nimbusds-jwt = "9.37.3"
rocket-starter = "2.3.0"
jsqlparser = "4.9"
lettucemod = "3.8.0"
minio = "8.5.9"
dnsjava = "3.5.3"
aliyun-oss = "3.17.4"
aviator = "5.4.1"
protobuf-java = "4.26.1"
grpc-java = "1.63.0"
google-protobuf-plugins = "0.9.4"
google-osdetector-plugins = "1.7.3"
jexl3 = "3.3"
mvel2 = "2.5.2.Final"
disruptor = "4.0.0"
spring-asciidoctor = "0.0.7"
spring-javaformat = "0.0.41"
compile-testing = "0.21.0"

[libraries]
spring-boot-admin-dependencies = { group = "de.codecentric", name = "spring-boot-admin-dependencies", version.ref = "spring-admin" }

#springdoc-openapi-all
openapi-common = { group = "org.springdoc", name = "springdoc-openapi-starter-common", version.ref = "springdoc" }
openapi-webflux-api = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-api", version.ref = "springdoc" }
openapi-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
openapi-webmvc-api = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-api", version.ref = "springdoc" }
openapi-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

#pagehelper-all
pagehelper = { group = "com.github.pagehelper", name = "pagehelper", version.ref = "pagehelper" }
pagehelper-starter = { group = "com.github.pagehelper", name = "pagehelper-spring-boot-starter", version.ref = "pagehelper-starter" }

#mybatis-all
mybatis-starter = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-starter", version.ref = "spring-mybatis" }
mybatis-autoconfigure = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-autoconfigure", version.ref = "spring-mybatis" }
mybatis-spring = { group = "org.mybatis", name = "mybatis-spring", version.ref = "spring-mybatis" }
mybatis = { group = "org.mybatis", name = "mybatis", version.ref = "mybatis" }

#redisson-all
redisson-starter = { group = "org.redisson", name = "redisson-spring-boot-starter", version.ref = "redisson" }
redisson = { group = "org.redisson", name = "redisson", version.ref = "redisson" }
redisson-spring-data = { group = "org.redisson", name = "redisson-spring-data-31", version.ref = "redisson" }

#clickhouse-all
clickhouse-jdbc = { group = "com.clickhouse", name = "clickhouse-jdbc", version.ref = "clickhouse" }
clickhouse-r2dbc = { group = "com.clickhouse", name = "clickhouse-r2dbc", version.ref = "clickhouse" }
clickhouse-client = { group = "com.clickhouse", name = "clickhouse-client", version.ref = "clickhouse" }

#mapstruct-all
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "mapstruct-lombok" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
easyexcel = { group = "com.alibaba", name = "easyexcel", version.ref = "easyexcel" }
spotbugs-annotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version.ref = "spotbugs-annotations" }
curator-recipes = { group = "org.apache.curator", name = "curator-recipes", version.ref = "curator" }
browscap-java = { group = "com.blueconic", name = "browscap-java", version.ref = "browscap-java" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
yauaa = { group = "nl.basjes.parse.useragent", name = "yauaa", version.ref = "yauaa" }
google-javase = { group = "com.google.zxing", name = "javase", version.ref = "google-javase" }
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbusds-jwt" }
rocketmq-boot-starter = { group = "org.apache.rocketmq", name = "rocketmq-spring-boot-starter", version.ref = "rocket-starter" }
jsqlparser = { group = "com.github.jsqlparser", name = "jsqlparser", version.ref = "jsqlparser" }
lettucemod = { group = "com.redis", name = "lettucemod", version.ref = "lettucemod" }
minio = { group = "io.minio", name = "minio", version.ref = "minio" }
dnsjava = { group = "dnsjava", name = "dnsjava", version.ref = "dnsjava" }
aliyun-oss = { group = "com.aliyun.oss", name = "aliyun-sdk-oss", version.ref = "aliyun-oss" }
aviator = { group = "com.googlecode.aviator", name = "aviator", version.ref = "aviator" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf-java" }
protobuf-java-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf-java" }
grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version.ref = "grpc-java" }
commons-jexl3 = { group = "org.apache.commons", name = "commons-jexl3", version.ref = "jexl3" }
mvel2 = { group = "org.mvel", name = "mvel2", version.ref = "mvel2" }
disruptor = { group = "com.lmax", name = "disruptor", version.ref = "disruptor" }
spring-asciidoctor = { group = "io.spring.asciidoctor.backends", name = "spring-asciidoctor-backends", version.ref = "spring-asciidoctor" }
compile-testing = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compile-testing" }

[bundles]
springdoc-openapi-all = ["openapi-common", "openapi-webflux-api", "openapi-webflux-ui", "openapi-webmvc-api", "openapi-webmvc-ui"]
pagehelper-all = ["pagehelper", "pagehelper-starter"]
mybatis-all = ["mybatis", "mybatis-spring", "mybatis-autoconfigure", "mybatis-starter"]
redisson-all = ["redisson", "redisson-starter", "redisson-spring-data"]
clickhouse-all = ["clickhouse-jdbc", "clickhouse-r2dbc", "clickhouse-client"]
mapstruct-all = ["mapstruct", "mapstruct-processor", "lombok-mapstruct"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
asciidoctor-jvm = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor-jvm" }
