[versions]
spring-boot = "3.4.4"
kotlin = "2.1.20"
pagehelper-starter = "2.1.0"
mybatis = "3.5.19"
mybatis-spring = "3.0.4"
mybatis-boot = "3.0.4"
guava = "33.4.6-jre"
fastexcel = "1.1.0"
redisson = "3.45.1"
clickhouse = "0.7.2"
mapstruct = "1.6.3"
mapstruct-lombok = "0.2.0"
curator = "5.8.0"
asciidoctor-jvm = "4.0.4"
browscap-java = "1.4.5"
auto-service = "1.1.1"
yauaa = "7.30.0"
springdoc = "2.8.6"
google-javase = "3.5.3"
spring-admin = "3.4.5"
nimbusds-jwt = "10.1"
jsqlparser = "5.1"
lettucemod = "4.2.1"
minio = "8.5.17"
aviator = "5.4.3"
protobuf-java = "4.30.2"
grpc-java = "1.71.0"
google-protobuf-plugins = "0.9.5"
google-osdetector-plugins = "1.7.3"
jexl3 = "3.4.0"
mvel2 = "2.5.2.Final"
disruptor = "4.0.0"
spring-asciidoctor = "0.0.7"
spring-javaformat = "0.0.43"
compile-testing = "0.21.0"
okhttp = "4.12.0"
spotbugs-annotations = "4.9.3"

[libraries]
spring-boot-admin-dependencies = { group = "de.codecentric", name = "spring-boot-admin-dependencies", version.ref = "spring-admin" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }

#springdoc-openapi-all
openapi-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
openapi-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

pagehelper-starter = { group = "com.github.pagehelper", name = "pagehelper-spring-boot-starter", version.ref = "pagehelper-starter" }

#mybatis-all
mybatis-starter = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-starter", version.ref = "mybatis-boot" }
mybatis-autoconfigure = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-autoconfigure", version.ref = "mybatis-boot" }
mybatis-spring = { group = "org.mybatis", name = "mybatis-spring", version.ref = "mybatis-spring" }
mybatis = { group = "org.mybatis", name = "mybatis", version.ref = "mybatis" }

#redisson-all
redisson-starter = { group = "org.redisson", name = "redisson-spring-boot-starter", version.ref = "redisson" }
redisson = { group = "org.redisson", name = "redisson", version.ref = "redisson" }
redisson-spring-data = { group = "org.redisson", name = "redisson-spring-data-34", version.ref = "redisson" }

#clickhouse-all
clickhouse-jdbc = { group = "com.clickhouse", name = "clickhouse-jdbc", version.ref = "clickhouse" }
clickhouse-r2dbc = { group = "com.clickhouse", name = "clickhouse-r2dbc", version.ref = "clickhouse" }
clickhouse-client = { group = "com.clickhouse", name = "clickhouse-client", version.ref = "clickhouse" }

#mapstruct-all
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "mapstruct-lombok" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
fastexcel = { group = "cn.idev.excel", name = "fastexcel", version.ref = "fastexcel" }
curator-recipes = { group = "org.apache.curator", name = "curator-recipes", version.ref = "curator" }
browscap-java = { group = "com.blueconic", name = "browscap-java", version.ref = "browscap-java" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
yauaa = { group = "nl.basjes.parse.useragent", name = "yauaa", version.ref = "yauaa" }
google-javase = { group = "com.google.zxing", name = "javase", version.ref = "google-javase" }
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbusds-jwt" }
jsqlparser = { group = "com.github.jsqlparser", name = "jsqlparser", version.ref = "jsqlparser" }
lettucemod = { group = "com.redis", name = "lettucemod", version.ref = "lettucemod" }
minio = { group = "io.minio", name = "minio", version.ref = "minio" }
aviator = { group = "com.googlecode.aviator", name = "aviator", version.ref = "aviator" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf-java" }
protobuf-java-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf-java" }
grpc-java = { group = "io.grpc", name = "protoc-gen-grpc-java", version.ref = "grpc-java" }
commons-jexl3 = { group = "org.apache.commons", name = "commons-jexl3", version.ref = "jexl3" }
mvel2 = { group = "org.mvel", name = "mvel2", version.ref = "mvel2" }
disruptor = { group = "com.lmax", name = "disruptor", version.ref = "disruptor" }
spring-asciidoctor = { group = "io.spring.asciidoctor.backends", name = "spring-asciidoctor-backends", version.ref = "spring-asciidoctor" }
compile-testing = { group = "com.google.testing.compile", name = "compile-testing", version.ref = "compile-testing" }
spotbugs-annotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version.ref = "spotbugs-annotations" }

[bundles]
mybatis-all = ["mybatis", "mybatis-spring", "mybatis-autoconfigure", "mybatis-starter"]
redisson-all = ["redisson", "redisson-starter", "redisson-spring-data"]
mapstruct-all = ["mapstruct", "mapstruct-processor", "lombok-mapstruct"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
asciidoctor-jvm = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor-jvm" }
google-protobuf = { id = "com.google.protobuf", version.ref = "google-protobuf-plugins" }
spring-javaformat = { id = "io.spring.javaformat", version.ref = "spring-javaformat" }
