spring:
  data:
    redis:
      host: livk.com
      password: 123456
      lettuce:
        pool:
          max-active: 1024
          max-wait: 10000
          max-idle: 200
      timeout: 10000
server:
  port: 6378
