server:
  port: 9515

spring:
  datasource:
    url: jdbc:mysql://livk.com:3306/mybatis_type
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:data.sql
      mode: always
